import type { Collection, Product, SiteSettings } from "./types";

const img = (n: number) => `/placeholders/candle-${String(n).padStart(2, "0")}.svg`;
const SIZE_CHART = "/placeholders/size-chart.svg";

export const seedSettings: SiteSettings = {
  businessName: "Sugandha Candles",
  tagline: "Hand-poured candles, made in small batches.",
  aboutBlurb:
    "We pour every candle by hand in our workshop — soy and coconut wax, cotton wicks, and fragrance blends we build ourselves. This catalogue carries our full range with sizes and pricing, so you have everything in one place. Buy one piece or a thousand.",
  instagramHandle: "sugandha_candles_",
  email: "sugandha.workspace@gmail.com",
  phone: "+91 99999 99999",
  addressLines: ["Sugandha Candles", "Workshop No. 12, Industrial Area", "Jaipur, Rajasthan 302013"],
  currency: "INR",
  termsIntro:
    "These terms apply to all orders placed with Sugandha Candles. They are written plainly so there is nothing to decode. If anything here does not suit your order, tell us — most of it can be discussed.",
  termsSections: [
    {
      heading: "Payment",
      body: [
        "65% advance to confirm the order. The remaining 35% before dispatch.",
        "Payment by NEFT, RTGS, IMPS or UPI to our current account. Bank details are shared on the proforma invoice.",
        "For repeat buyers with three or more completed orders, we can move to 50% advance.",
        "We do not accept cash on delivery or post-dated cheques.",
      ],
    },
    {
      heading: "Order size",
      body: [
        "There is no minimum order. A single piece is welcome, and so is a container load.",
        "You may mix designs and fragrances freely within one order.",
        "Slab pricing is worked out per design, so buying more of one design is what brings the rate down.",
      ],
    },
    {
      heading: "Pricing",
      body: [
        "All prices are per piece and exclude GST. GST is charged at 18%.",
        "Slab pricing shown on each product applies automatically once you cross the listed quantity.",
        "Prices hold for 30 days from the date this catalogue link is shared. Wax and fragrance oil costs move, and we would rather requote than surprise you.",
      ],
    },
    {
      heading: "Lead time",
      body: [
        "Stocked designs: 7 to 10 working days from advance payment.",
        "Custom fragrance, colour or vessel: 18 to 22 working days.",
        "Festive season (September to November) adds roughly a week. Plan backwards from your launch date.",
      ],
    },
    {
      heading: "Customisation",
      body: [
        "Private label with your own printed label and box is available from 500 pieces per design.",
        "Custom fragrance development is free above 1,000 pieces, otherwise a one-time ₹6,000 development charge applies.",
        "Vessel colour matching needs a Pantone reference and 1,000 pieces minimum.",
      ],
    },
    {
      heading: "Samples",
      body: [
        "Sample sets are charged at 2x the listed piece price plus actual courier.",
        "Sample cost is adjusted against your first bulk order of the same design.",
        "Samples ship in 3 to 4 working days.",
      ],
    },
    {
      heading: "Packing and shipping",
      body: [
        "Every candle is bubble-wrapped and packed in 5-ply corrugated cartons with corner protection.",
        "Prices are ex-workshop. Freight is at your account, or we can arrange it and bill at actuals.",
        "Transit insurance is available on request and strongly recommended for glass vessels.",
      ],
    },
    {
      heading: "Breakage and returns",
      body: [
        "Report transit breakage within 48 hours of delivery with photographs of the outer carton and the damaged pieces.",
        "Verified breakage is replaced free in your next dispatch.",
        "We do not accept returns for change of mind, or on custom and private-label production.",
      ],
    },
    {
      heading: "Colour and finish",
      body: [
        "These are hand-poured products. Slight variation in colour, surface finish and frosting between batches is normal and is not a defect.",
        "Natural soy wax may develop a light crystalline pattern on the surface. It does not affect burn quality.",
      ],
    },
  ],
};

export const seedCollections: Collection[] = [
  {
    id: "c1",
    slug: "signature-jars",
    name: "Signature Jars",
    tagline: "Our core range, in glass",
    description:
      "The candles we are known for. Poured into thick amber and frosted glass, with a clean burn and a scent throw that fills a room without shouting. This is where most buyers start.",
    coverImage: img(1),
    sortOrder: 1,
  },
  {
    id: "c2",
    slug: "pillars-and-blocks",
    name: "Pillars & Blocks",
    tagline: "Unscented, architectural",
    description:
      "Free-standing candles in clean geometry. Mostly unscented, made for styling — table settings, retail displays, photo shoots. Long burn, low drip.",
    coverImage: img(4),
    sortOrder: 2,
  },
  {
    id: "c3",
    slug: "tealights-and-votives",
    name: "Tealights & Votives",
    tagline: "Small format, high volume",
    description:
      "Our highest-volume line. Ideal for hospitality, events and gifting inserts. Priced to move in quantity.",
    coverImage: img(7),
    sortOrder: 3,
  },
  {
    id: "c4",
    slug: "festive-and-gifting",
    name: "Festive & Gifting",
    tagline: "Diwali, weddings, corporate",
    description:
      "Boxed sets and seasonal designs built for gifting. Private label available across this range from 500 pieces.",
    coverImage: img(10),
    sortOrder: 4,
  },
];

export const seedProducts: Product[] = [
  {
    id: "p1",
    slug: "amber-oud-jar",
    name: "Amber Oud Jar",
    collectionSlug: "signature-jars",
    tagline: "Warm, resinous, a little smoky",
    description:
      "Our best-selling jar. Oud and amber over a base of sandalwood, poured into thick amber glass with a matching wooden lid. Burns clean to the bottom with a full melt pool from the first light.",
    images: [img(1), img(2), img(3)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Amber, Oud, Sandalwood",
    waxType: "Soy & Coconut blend",
    wickType: "Cotton, single",
    burnTimeHours: 45,
    heightCm: 9.5,
    diameterCm: 8,
    weightGrams: 200,
    basePrice: 340,
    priceTiers: [
      { minQty: 1, price: 340 },
      { minQty: 300, price: 315 },
      { minQty: 1000, price: 285 },
    ],
    packaging: "Kraft box, 12 pieces per carton",
    inStock: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: "p2",
    slug: "vetiver-cedar-jar",
    name: "Vetiver Cedar Jar",
    collectionSlug: "signature-jars",
    tagline: "Dry, green, grounding",
    description:
      "Vetiver root and cedarwood with a thin line of black pepper. Frosted white glass, matte finish. The one buyers pick when they want something that reads as masculine without being heavy.",
    images: [img(2), img(3), img(1)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Vetiver, Cedarwood, Black Pepper",
    waxType: "Soy & Coconut blend",
    wickType: "Cotton, single",
    burnTimeHours: 45,
    heightCm: 9.5,
    diameterCm: 8,
    weightGrams: 200,
    basePrice: 340,
    priceTiers: [
      { minQty: 1, price: 340 },
      { minQty: 300, price: 315 },
      { minQty: 1000, price: 285 },
    ],
    packaging: "Kraft box, 12 pieces per carton",
    inStock: true,
    featured: true,
    sortOrder: 2,
  },
  {
    id: "p3",
    slug: "tuberose-grande",
    name: "Tuberose Grande",
    collectionSlug: "signature-jars",
    tagline: "Three wicks, whole-room throw",
    description:
      "Our largest jar, with three cotton wicks for an even melt across a wide surface. Indian tuberose lifted with jasmine and a touch of green stem. Built for hotel lobbies and large living rooms.",
    images: [img(3), img(1), img(5)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Tuberose, Jasmine, Green Stem",
    waxType: "Soy & Coconut blend",
    wickType: "Cotton, triple",
    burnTimeHours: 80,
    heightCm: 11,
    diameterCm: 13,
    weightGrams: 520,
    basePrice: 790,
    priceTiers: [
      { minQty: 1, price: 790 },
      { minQty: 200, price: 735 },
      { minQty: 600, price: 680 },
    ],
    packaging: "Rigid gift box, 6 pieces per carton",
    inStock: true,
    featured: true,
    sortOrder: 3,
  },
  {
    id: "p4",
    slug: "mogra-travel-tin",
    name: "Mogra Travel Tin",
    collectionSlug: "signature-jars",
    tagline: "Pocket size, screw lid",
    description:
      "Fresh mogra in a seamless aluminium tin with a screw lid. Light, unbreakable, and the easiest thing to add to a hamper or a hotel turndown tray.",
    images: [img(5), img(6), img(4)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Mogra, White Musk",
    waxType: "Soy",
    wickType: "Cotton, single",
    burnTimeHours: 20,
    heightCm: 4.5,
    diameterCm: 6,
    weightGrams: 90,
    basePrice: 165,
    priceTiers: [
      { minQty: 1, price: 165 },
      { minQty: 750, price: 148 },
      { minQty: 2000, price: 132 },
    ],
    packaging: "Shrink-wrapped, 24 pieces per carton",
    inStock: true,
    featured: false,
    sortOrder: 4,
  },
  {
    id: "p5",
    slug: "ribbed-pillar-tall",
    name: "Ribbed Pillar — Tall",
    collectionSlug: "pillars-and-blocks",
    tagline: "Unscented, 22cm",
    description:
      "A tall ribbed pillar in stearin-hardened wax that holds its edge in warm weather. Unscented by default so it never fights the food on the table. Available in six standard colours.",
    images: [img(4), img(6), img(8)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Unscented",
    waxType: "Paraffin & Stearin",
    wickType: "Braided cotton",
    burnTimeHours: 60,
    heightCm: 22,
    diameterCm: 7,
    weightGrams: 480,
    basePrice: 295,
    priceTiers: [
      { minQty: 1, price: 295 },
      { minQty: 400, price: 268 },
      { minQty: 1200, price: 240 },
    ],
    packaging: "Individually sleeved, 20 pieces per carton",
    inStock: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: "p6",
    slug: "ribbed-pillar-short",
    name: "Ribbed Pillar — Short",
    collectionSlug: "pillars-and-blocks",
    tagline: "Unscented, 12cm",
    description:
      "The shorter companion to the tall pillar, same diameter and finish. Sold as a pair or a stepped set of three in most retail orders.",
    images: [img(6), img(4), img(9)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Unscented",
    waxType: "Paraffin & Stearin",
    wickType: "Braided cotton",
    burnTimeHours: 32,
    heightCm: 12,
    diameterCm: 7,
    weightGrams: 260,
    basePrice: 195,
    priceTiers: [
      { minQty: 1, price: 195 },
      { minQty: 400, price: 178 },
      { minQty: 1200, price: 160 },
    ],
    packaging: "Individually sleeved, 30 pieces per carton",
    inStock: true,
    featured: false,
    sortOrder: 2,
  },
  {
    id: "p7",
    slug: "faceted-block",
    name: "Faceted Block",
    collectionSlug: "pillars-and-blocks",
    tagline: "Sculptural, sits flat",
    description:
      "A low geometric block that reads as an object first and a candle second. Popular with concept stores and for product photography props.",
    images: [img(9), img(8), img(4)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Unscented",
    waxType: "Paraffin & Stearin",
    wickType: "Braided cotton",
    burnTimeHours: 28,
    heightCm: 8,
    diameterCm: 10,
    weightGrams: 340,
    basePrice: 260,
    priceTiers: [
      { minQty: 1, price: 260 },
      { minQty: 400, price: 238 },
    ],
    packaging: "Foam-nested, 12 pieces per carton",
    inStock: false,
    featured: false,
    sortOrder: 3,
  },
  {
    id: "p8",
    slug: "unscented-tealights",
    name: "Unscented Tealights",
    collectionSlug: "tealights-and-votives",
    tagline: "4-hour burn, polycarbonate cup",
    description:
      "Standard tealights in clear polycarbonate cups, which look far better than aluminium on a table and cost only marginally more. Our highest-volume item.",
    images: [img(7), img(11), img(13)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Unscented",
    waxType: "Refined Paraffin",
    wickType: "Cotton, pre-tabbed",
    burnTimeHours: 4,
    heightCm: 1.6,
    diameterCm: 3.8,
    weightGrams: 12,
    basePrice: 9,
    priceTiers: [
      { minQty: 1, price: 9 },
      { minQty: 5000, price: 7.5 },
      { minQty: 20000, price: 6.2 },
    ],
    packaging: "Bags of 50, 1000 pieces per carton",
    inStock: true,
    featured: false,
    sortOrder: 1,
  },
  {
    id: "p9",
    slug: "scented-votive",
    name: "Scented Votive",
    collectionSlug: "tealights-and-votives",
    tagline: "Six fragrances, mix freely",
    description:
      "A proper votive with real fragrance load, meant to be burned in a holder. Available in six of our house fragrances, and you can mix them freely within one order.",
    images: [img(11), img(13), img(7)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Six house fragrances",
    waxType: "Soy",
    wickType: "Cotton, single",
    burnTimeHours: 12,
    heightCm: 5,
    diameterCm: 4.5,
    weightGrams: 55,
    basePrice: 62,
    priceTiers: [
      { minQty: 1, price: 62 },
      { minQty: 2000, price: 55 },
      { minQty: 8000, price: 47 },
    ],
    packaging: "Trays of 24, 480 pieces per carton",
    inStock: true,
    featured: true,
    sortOrder: 2,
  },
  {
    id: "p10",
    slug: "floating-lotus",
    name: "Floating Lotus",
    collectionSlug: "tealights-and-votives",
    tagline: "For water bowls and urlis",
    description:
      "Moulded lotus floaters that sit upright in water without tipping. Standard for wedding decor and temple orders through the festive season.",
    images: [img(13), img(7), img(15)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Unscented",
    waxType: "Refined Paraffin",
    wickType: "Cotton, pre-tabbed",
    burnTimeHours: 5,
    heightCm: 2.5,
    diameterCm: 6.5,
    weightGrams: 28,
    basePrice: 16,
    priceTiers: [
      { minQty: 1, price: 16 },
      { minQty: 5000, price: 13.5 },
    ],
    packaging: "Bags of 25, 500 pieces per carton",
    inStock: true,
    featured: false,
    sortOrder: 3,
  },
  {
    id: "p11",
    slug: "diwali-gift-set-of-four",
    name: "Diwali Gift Set of Four",
    collectionSlug: "festive-and-gifting",
    tagline: "Boxed, ready to gift",
    description:
      "Four small jars in our four festive fragrances, in a rigid box with a printed sleeve. The sleeve can carry your brand from 500 sets. Our single biggest corporate line.",
    images: [img(10), img(12), img(14)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Kesar, Gulab, Chandan, Kewda",
    waxType: "Soy",
    wickType: "Cotton, single",
    burnTimeHours: 18,
    heightCm: 5.5,
    diameterCm: 5.5,
    weightGrams: 380,
    basePrice: 720,
    priceTiers: [
      { minQty: 1, price: 720 },
      { minQty: 500, price: 655 },
      { minQty: 2000, price: 590 },
    ],
    packaging: "Rigid box with sleeve, 8 sets per carton",
    inStock: true,
    featured: true,
    sortOrder: 1,
  },
  {
    id: "p12",
    slug: "brass-urli-with-floaters",
    name: "Brass Urli with Floaters",
    collectionSlug: "festive-and-gifting",
    tagline: "Vessel plus 12 floaters",
    description:
      "A spun brass urli with an antique finish, packed with twelve lotus floaters. Arrives assembled in a cloth bag, so it needs no work at your end before gifting.",
    images: [img(12), img(14), img(16)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Unscented floaters",
    waxType: "Refined Paraffin",
    wickType: "Cotton, pre-tabbed",
    burnTimeHours: 5,
    heightCm: 7,
    diameterCm: 20,
    weightGrams: 1150,
    basePrice: 1450,
    priceTiers: [
      { minQty: 1, price: 1450 },
      { minQty: 250, price: 1320 },
    ],
    packaging: "Cloth bag in carton, 4 pieces per carton",
    inStock: true,
    featured: false,
    sortOrder: 2,
  },
  {
    id: "p13",
    slug: "kesar-mithai-jar",
    name: "Kesar Mithai Jar",
    collectionSlug: "festive-and-gifting",
    tagline: "Seasonal, saffron and milk",
    description:
      "Saffron, cardamom and warm milk — it smells like a mithai shop in the best way. Produced only from August, and it sells out most years by mid-October.",
    images: [img(14), img(16), img(10)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Kesar, Cardamom, Milk",
    waxType: "Soy & Coconut blend",
    wickType: "Cotton, single",
    burnTimeHours: 45,
    heightCm: 9.5,
    diameterCm: 8,
    weightGrams: 200,
    basePrice: 375,
    priceTiers: [
      { minQty: 1, price: 375 },
      { minQty: 500, price: 342 },
    ],
    packaging: "Printed box, 12 pieces per carton",
    inStock: true,
    featured: false,
    sortOrder: 3,
  },
  {
    id: "p14",
    slug: "corporate-desk-duo",
    name: "Corporate Desk Duo",
    collectionSlug: "festive-and-gifting",
    tagline: "Two tins, slim box",
    description:
      "Two travel tins in a slim board box that fits a courier envelope. Built for large-headcount corporate gifting where shipping cost decides the budget.",
    images: [img(16), img(10), img(12)],
    sizeChartImage: SIZE_CHART,
    fragrance: "Mogra & Vetiver",
    waxType: "Soy",
    wickType: "Cotton, single",
    burnTimeHours: 20,
    heightCm: 5,
    diameterCm: 13,
    weightGrams: 240,
    basePrice: 395,
    priceTiers: [
      { minQty: 1, price: 395 },
      { minQty: 1000, price: 358 },
      { minQty: 5000, price: 320 },
    ],
    packaging: "Slim board box, 20 sets per carton",
    inStock: true,
    featured: false,
    sortOrder: 4,
  },
];
